name: Deploy to Firebase

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the appropriate Node.js version

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      run: echo "${{ secrets.FIREBASE_TOKEN }}" | firebase login:ci --token

    - name: Build and Deploy
      run: |
        # Install dependencies
        npm install

        # Deploy to Firebase
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
